blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/Techopolis/Perspective-Studio/discussions
    about: Ask questions, share ideas, or connect with the community
